/******************************************************************
 * File: rql_token.cc
 *
 * This file was automatically generated by CppCC Version 0.0.8
 * DO NOT EDIT MANUALLY
 ******************************************************************/


#include "rql_token.hh"


const int cppcc::RqlToken::eof = 0;
const int cppcc::RqlToken::ws = 1;
const int cppcc::RqlToken::LONG_COMMENT1 = 2;
const int cppcc::RqlToken::LONG_COMMENT2 = 3;
const int cppcc::RqlToken::LONG_COMMENT3 = 4;
const int cppcc::RqlToken::LONG_COMMENT4 = 5;
const int cppcc::RqlToken::LONG_COMMENT5 = 6;
const int cppcc::RqlToken::LONG_COMMENT = 7;
const int cppcc::RqlToken::DELETE = 8;
const int cppcc::RqlToken::SET = 9;
const int cppcc::RqlToken::INSERT = 10;
const int cppcc::RqlToken::DISTINCT = 11;
const int cppcc::RqlToken::WHERE = 12;
const int cppcc::RqlToken::OR = 13;
const int cppcc::RqlToken::AND = 14;
const int cppcc::RqlToken::NOT = 15;
const int cppcc::RqlToken::GROUPBY = 16;
const int cppcc::RqlToken::ORDERBY = 17;
const int cppcc::RqlToken::SORT_ASC = 18;
const int cppcc::RqlToken::SORT_DESC = 19;
const int cppcc::RqlToken::LIMIT = 20;
const int cppcc::RqlToken::OFFSET = 21;
const int cppcc::RqlToken::DATE = 22;
const int cppcc::RqlToken::DATETIME = 23;
const int cppcc::RqlToken::RQLNULL = 24;
const int cppcc::RqlToken::SEMICOLON = 25;
const int cppcc::RqlToken::COLON = 26;
const int cppcc::RqlToken::COMA = 27;
const int cppcc::RqlToken::LPAREN = 28;
const int cppcc::RqlToken::RPAREN = 29;
const int cppcc::RqlToken::CMP_OP = 30;
const int cppcc::RqlToken::BOOLEAN = 31;
const int cppcc::RqlToken::SYMBOL = 32;
const int cppcc::RqlToken::FLOAT = 33;
const int cppcc::RqlToken::INT = 34;
const int cppcc::RqlToken::SUBSTITUTE = 35;
const int cppcc::RqlToken::STRING = 36;
const int cppcc::RqlToken::ADD_OP = 37;
const int cppcc::RqlToken::MUL_OP = 38;



/* End of file. */
